steps:

  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      echo Installing packages
      yarn && yarn build
      echo Start building windows application
      echo Windows build is complete
    displayName: "Build Windows app"
    env:
      GH_TOKEN: $(GH_TOKEN)
  - script: |
      cd dist
      ls
    displayName: "Validate build"
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/build
      contents: (*.exe)
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: "Copying files"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: win
    displayName: "Publish artifacts"
